"""Add user&github_user table

Revision ID: dc9232250fee
Revises: 
Create Date: 2021-05-08 16:04:03.179160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9232250fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_userinfo',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=40), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('github_auth', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('github_userinfo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('nickname', sa.String(
                        length=255), nullable=True),
                    sa.Column('profile_photo', sa.String(
                        length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['email'], ['local_userinfo.email'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_userinfo')
    op.drop_table('local_userinfo')
    # ### end Alembic commands ###
