"""Fix user table

Revision ID: e2e11e391b3d
Revises: dc9232250fee
Create Date: 2021-05-08 16:12:07.025412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e11e391b3d'
down_revision = 'dc9232250fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_userinfo', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('local_userinfo', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('local_userinfo', 'github_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_userinfo', 'github_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('local_userinfo', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('local_userinfo', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
